import type { Metadata } from "next";
import "./globals.css";
import { Oswald, Barlow, Bebas_Neue } from "next/font/google"

export const metadata: Metadata = {
  title: "Campus Fair - IKAMAMIIND 2100",
  description: "Generated by create next app",
};

const oswald = Oswald({
  variable: "--font-display",
  subsets: ["latin"],
  weight: [
    "500",
    "600",
    "700",
  ],
});

const barlow = Barlow({
  variable: "--font-body",
  subsets: ["latin"],
  weight: [
    "400",
    "500",
    "600",
    "700",
  ],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-display",
  subsets: ["latin"],
  weight: "400",
});

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({
  children,
}: RootLayoutProps) {
  return (
    <html
      lang="en"
      className={`${oswald.variable} ${barlow.variable} ${bebasNeue.variable} h-full antialiased`}
    >
      <body className="relativ w-full h-auto">
        {children}
      </body>
    </html>
  );
}
